### ISSUE TITLE
[Design] 프로필 이미지 컴포넌트 디자인

### ISSUE THREAD

**Issue by Ga-Zero** [prgrms-web-devcourse-final-project/WEB1_1_ALL-I_FE#37]
## 설명
회원가입, 마이페이지, 그룹원 프로필 이미지 css 설정 컴포넌트

## TODO List
- [x] 회원가입, 마이페이지, 마이페이지 수정 120 * 120
- [x] 그룹 페이지의 그룹원 리스트 30 * 30
- [x] 그룹 페이지 일정, 투두 생성의 팀원 선택 리스트 20 * 20

**참고 자료**
