### ISSUE TITLE
[feat] 각 페이지 컴포넌트 생성및 라우트 파일 정리

### ISSUE THREAD

**Issue by wilderif** [prgrms-web-devcourse-final-project/WEB1_1_ALL-I_FE#5]
## 설명
각 페이지 컴포넌트 생성및 라우트 파일 정리

## TODO List
- [x] 프로젝트 폴더구조
- [ ] 페이지 컴포넌트 생성
- [ ] 라우트 파일 정리
- [ ] App에 적용 및 테스트
