### ISSUE TITLE
[Refactor] calendar 폴더 정리

### ISSUE THREAD

**Issue by wilderif** [prgrms-web-devcourse-final-project/WEB1_1_ALL-I_FE#60]
## 설명
새로운 기능에 대한 명확하고 간결한 설명을 작성해 주세요.

## TODO List
- [x]  style 파일 컨벤션 맞춰서 정리
- [x]  주간 달력 폴더, 컴포넌트 삭제
- [x]  폴더이름 대문자 변경

**참고 자료**
