### ISSUE TITLE
[Design] 주간 달력 스타일링

### ISSUE THREAD

**Issue by wilderif** [prgrms-web-devcourse-final-project/WEB1_1_ALL-I_FE#80]
## 설명
새로운 기능에 대한 명확하고 간결한 설명을 작성해 주세요.

## TODO List
- [x]  ToDo 더미데이터 추가
- [x]  주간 달력 일정 개수 제한 제거
- [ ]  주간 달력 투두 스타일링 (가능하면 클릭 가능하도록)

**참고 자료**
