### ISSUE TITLE
[Refactor] layout 관련 컴포넌트 수정

### ISSUE THREAD

**Issue by wilderif** [prgrms-web-devcourse-final-project/WEB1_1_ALL-I_FE#87]
## 설명

루트레이아웃, 헤더, 네비바 컴포넌트 레이아웃 조정

## TODO List
- [ ]  헤더, 네비바 아이콘 크기 및 사이드 마진 값 통일
- [ ]  루트 레이아웃 사이드 마진, 상단 마진 추가
- [ ]  각 페이지 레이아웃 확인

**참고 자료**
