### ISSUE TITLE
[Feature] 챗봇 컴포넌트 제작

### ISSUE THREAD

**Issue by Ga-Zero** [prgrms-web-devcourse-final-project/WEB1_1_ALL-I_FE#90]
## 설명
챗봇 페이지에서 필요한 컴포넌트들을 생성

## TODO List
- [x] 채팅 말풍선 컴포넌트
- [x] 채팅 입력 컴포넌트
- [x] 챗옵션 컴포넌트
- [x] 카테고리 선택 컴포넌트
- [x] 채팅 예시 텍스트 컴포넌트
