### ISSUE TITLE
[Feature] main 페이지 기능 추가

### ISSUE THREAD

**Issue by wilderif** [prgrms-web-devcourse-final-project/WEB1_1_ALL-I_FE#98]
## 설명
main 페이지 수정 및 기능 추가

## TODO List
- [ ] 레이아웃, UI 요소 수정
- [ ] 달력에 사용한 더미데이터, css파일에 정의된 카테고리 색상 사용하도록 수정
- [ ] 달력 클릭 필터링 기능 추가
- [ ] MainList 컴포넌트 레이아웃, (로직) 수정
